# Based off https://github.com/vlang/docker

FROM thevlang/vlang:alpine-build AS builder

WORKDIR /opt/vlang

RUN git clone https://github.com/vlang/v /opt/vlang && make VFLAGS='-cc gcc' && v -version

FROM thevlang/vlang:alpine-base AS runtime

ENV VFLAGS="-cc gcc"

RUN apk --no-cache add \
    gcc musl-dev git libexecinfo-static libexecinfo-dev libc-dev make

COPY --from=builder /opt/vlang /opt/vlang

ENV TWITTER_BEARER_TOKEN=""

WORKDIR /opt/vtik

RUN git clone https://github.com/Sharqo78/VTik
RUN v up
RUN v -prod /opt/vtik/VTik/src/vtik-web.v -o /opt/vtik/vtik-web 
RUN rm -rf /opt/vtik/VTik

ENTRYPOINT /opt/vtik/vtik-web