# Based off https://github.com/vlang/docker

FROM thevlang/vlang:alpine-build AS builder

WORKDIR /opt/vlang

RUN git clone https://github.com/vlang/v /opt/vlang && make VFLAGS='-cc gcc' && v -version

FROM thevlang/vlang:alpine-base AS runtime

ENV VFLAGS="-cc gcc"

RUN apk --no-cache add \
    gcc musl-dev git libexecinfo-static libexecinfo-dev libc-dev

COPY --from=builder /opt/vlang /opt/vlang

RUN v install dariotarantini.vgram

ENV TELEGRAM_TOKEN=""
ENV TWITTER_BEARER_TOKEN=""

WORKDIR /opt/vtik

RUN git clone https://github.com/Sharqo78/VTik
RUN v /opt/vtik/VTik/src/vtik-telegram.v -o /opt/vtik/vtik-telegram -d use_openssl
RUN rm -rf /opt/vtik/VTik

ENTRYPOINT /opt/vtik/vtik-telegram